Traceback (most recent call last):
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.close('all'); fig, ax = plt.subplots(1, figsize=(9, 5))

def update(gamma):
    t, y = scipy.signal.dimpulse(([1-gamma, 0], [1, -gamma], 1), x0=0, n=30)
    ax.cla(); ax.plot(t, y[0], lw=4); 

interact(update, gamma=FloatSlider_nice(min=-1.1, max=2.1, step=0.01), msg_throttle=1);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-859dc7908603>[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m     [0max[0m[0;34m.[0m[0mcla[0m[0;34m([0m[0;34m)[0m[0;34m;[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mt[0m[0;34m,[0m [0my[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mlw[0m[0;34m=[0m[0;36m4[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;34m[0m[0m
[0;32m----> 7[0;31m [0minteract[0m[0;34m([0m[0mupdate[0m[0;34m,[0m [0mgamma[0m[0;34m=[0m[0mFloatSlider_nice[0m[0;34m([0m[0mmin[0m[0;34m=[0m[0;34m-[0m[0;36m1.1[0m[0;34m,[0m [0mmax[0m[0;34m=[0m[0;36m2.1[0m[0;34m,[0m [0mstep[0m[0;34m=[0m[0;36m0.01[0m[0;34m)[0m[0;34m,[0m [0mmsg_throttle[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'interact' is not defined
NameError: name 'interact' is not defined

